services:
  - type: web
    name: bullish-backend
    rootDir: BullishorBust/Bullishorbust/Backend/
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: 24.4.1
